FROM hivdb/sierra-ebv:latest AS sierra-ebv
FROM hivdb/sierra-hbv:latest AS sierra-hbv

FROM hivdb/sierra:latest
COPY --from=sierra-ebv /usr/share/tomcat/webapps/Sierra-EBV.war /usr/share/tomcat/webapps
COPY --from=sierra-hbv /usr/share/tomcat/webapps/Sierra-HBV.war /usr/share/tomcat/webapps
